### ISSUE TITLE
关于实现的一些看法

### ISSUE THREAD

**Issue by vizee** [jamesruan/cqueue#1]
paper 用的 CAS 操作确切说是 DCAS, 在 x86 架构实现的话对应 lock cmpxchg8b/16b.
手撸汇编是可以实现这个指令的, 但是会有一个内存对齐的要求, go 默认 64bits 对齐, cmpxchg16b 需要 128bits 对齐, 但也好解决.

其实用 version 解决 ABA 已经是常用技巧了, 如是指针级位宽只能用 DCAS, 但是也可以变成 index+version, 这样只要 go 自带的 CompareAndSwapUint64 就 ojbk 了

**Comment by jamesruan** [comment]
只是之前看到了这个paper，没理解透。

具体实现的时候这个双倍宽度的CAS就不好弄了。
想想从实用出发还是用lock版本的好了。
